/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x800200U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK 0x10U /*!< GPIO3 and GPIO8 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_09 (coord F14), LED_F14 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_F14_PERIPHERAL                                  GPIO6   /*!< Peripheral name */
#define BOARD_INITPINS_LED_F14_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_F14_CHANNEL                                        9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_F14_GPIO                                        GPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_F14_GPIO_PIN                                       9U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_F14_GPIO_PIN_MASK                          (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_F14_PORT                                        GPIO6   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_F14_PIN                                            9U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_F14_PIN_MASK                               (1U << 9U)   /*!< PORT pin mask */

/* GPIO_SD_B1_04 (coord P2), SD_CD */
/* Routed pin properties */
#define BOARD_INITPINS_SD_CD_PERIPHERAL                                    GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_SD_CD_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SD_CD_CHANNEL                                          4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SD_CD_GPIO                                          GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SD_CD_GPIO_PIN                                         4U   /*!< GPIO pin number */
#define BOARD_INITPINS_SD_CD_GPIO_PIN_MASK                            (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SD_CD_PORT                                          GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SD_CD_PIN                                              4U   /*!< PORT pin number */
#define BOARD_INITPINS_SD_CD_PIN_MASK                                 (1U << 4U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (coord K10), SD_PWREN */
/* Routed pin properties */
#define BOARD_INITPINS_SD_PWREN_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_SD_PWREN_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SD_PWREN_CHANNEL                                      23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SD_PWREN_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SD_PWREN_GPIO_PIN                                     23U   /*!< GPIO pin number */
#define BOARD_INITPINS_SD_PWREN_GPIO_PIN_MASK                        (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SD_PWREN_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SD_PWREN_PIN                                          23U   /*!< PORT pin number */
#define BOARD_INITPINS_SD_PWREN_PIN_MASK                             (1U << 23U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
